[package]
name = "mock-service"
version = "0.0.9"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread", "macros", "fs"] }
axum = "0.8.8"

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = "z"
strip = true
