services:
  mock-service:
    build:
      context: ./
      dockerfile: Containerfile
    image: localhost/mock-service
    environment:
      SECRET_KEY: "${SECRET_KEY:-test}"
    ports:
      - "8000:8000"
    networks:
      common:
        aliases:
          - mock-service

networks:
  common:
    driver: bridge
